# Generated by Django 3.0.4 on 2020-06-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200628_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], default='Notapproved', max_length=200),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='status',
            field=models.CharField(blank=True, choices=[('Dues', 'dues'), ('Nodues', 'nodues')], max_length=200),
        ),
        migrations.AlterField(
            model_name='exams',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], default='Notapproved', max_length=200),
        ),
        migrations.AlterField(
            model_name='exams',
            name='status',
            field=models.CharField(blank=True, choices=[('Dues', 'dues'), ('Nodues', 'nodues')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_1st_year',
            name='approval_accounts',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_1st_year',
            name='approval_exams',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_1st_year',
            name='approval_hod',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], default='Notapproved', max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_1st_year',
            name='approval_hostel',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_1st_year',
            name='approval_library',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_1st_year',
            name='approval_transport',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_auto',
            name='approval_accounts',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_auto',
            name='approval_exams',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_auto',
            name='approval_hod',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], default='Notapproved', max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_auto',
            name='approval_hostel',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_auto',
            name='approval_library',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_auto',
            name='approval_transport',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_civil',
            name='approval_accounts',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_civil',
            name='approval_exams',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_civil',
            name='approval_hod',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], default='Notapproved', max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_civil',
            name='approval_hostel',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_civil',
            name='approval_library',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_civil',
            name='approval_transport',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_cse',
            name='approval_accounts',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_cse',
            name='approval_exams',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_cse',
            name='approval_hod',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], default='Notapproved', max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_cse',
            name='approval_hostel',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_cse',
            name='approval_library',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_cse',
            name='approval_transport',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_ece',
            name='approval_accounts',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_ece',
            name='approval_exams',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_ece',
            name='approval_hod',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], default='Notapproved', max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_ece',
            name='approval_hostel',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_ece',
            name='approval_library',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_ece',
            name='approval_transport',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_management',
            name='approval_accounts',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_management',
            name='approval_exams',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_management',
            name='approval_hod',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], default='Notapproved', max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_management',
            name='approval_hostel',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_management',
            name='approval_library',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_management',
            name='approval_transport',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_me',
            name='approval_accounts',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_me',
            name='approval_exams',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_me',
            name='approval_hod',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], default='Notapproved', max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_me',
            name='approval_hostel',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_me',
            name='approval_library',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hod_me',
            name='approval_transport',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], default='Notapproved', max_length=200),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='status',
            field=models.CharField(blank=True, choices=[('Dues', 'dues'), ('Nodues', 'nodues')], max_length=200),
        ),
        migrations.AlterField(
            model_name='library',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], default='Notapproved', max_length=200),
        ),
        migrations.AlterField(
            model_name='library',
            name='no_of_books',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='library',
            name='status',
            field=models.CharField(blank=True, choices=[('Dues', 'dues'), ('Nodues', 'nodues')], max_length=200),
        ),
        migrations.AlterField(
            model_name='transport',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], default='Notapproved', max_length=200),
        ),
        migrations.AlterField(
            model_name='transport',
            name='status',
            field=models.CharField(blank=True, choices=[('Dues', 'dues'), ('Nodues', 'nodues')], max_length=200),
        ),
    ]
